# Generated by Django 5.2 on 2025-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.IntegerField(default=10),
        ),
    ]
