# Generated by Django 5.2 on 2025-04-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0002_question_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizroom',
            name='status',
            field=models.CharField(choices=[('NS', 'not started'), ('OG', 'on going'), ('EN', 'ended')], default='NS', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizroom',
            name='number_of_questions',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
