# Generated by Django 5.2 on 2025-04-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0003_quizroom_status_alter_quizroom_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizroom',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
