# Generated by Django 5.2 on 2025-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0004_alter_quizroom_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
