# Generated by Django 5.2 on 2025-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0005_alter_question_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(default=None, upload_to='question_image'),
        ),
    ]
